language: python
matrix:
  include:
    - python: 2.7
      dist: trusty
      env: RUN_SNYK=1
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
      env: RUN_LINTER=1
    - python: nightly
      dist: xenial
    - python: pypy
      dist: trusty
  allow_failures:
    - python: nightly

before_install:
  - git submodule update --init --recursive
  - git clone --recursive git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - pip install coverage coveralls
  - if [[ $RUN_LINTER ]]; then pip install pylint yapf; fi
  - |
    if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then
      sudo apt-get install -y nodejs;
      npm install -g snyk;
    fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then export MM_FORCE_EXT_TESTS=1; fi
  - CFLAGS="-Werror -Wall -Wextra" coverage run --source maxminddb setup.py test
  - if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind --file=requirements.txt; fi
  - if [[ $RUN_LINTER ]]; then pylint --rcfile .pylintrc maxminddb/*.py; fi
  - if [[ $RUN_LINTER ]]; then ./.travis-yapf.sh; fi

after_success:
  - coveralls
  - if [[ $RUN_SNYK && $SNYK_TOKEN && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then snyk monitor --org=maxmind --project-name=maxmind/MaxMind-DB-Reader-python; fi

notifications:
  email:
    recipients:
      - dev-ci@maxmind.com
    on_success: change
    on_failure: always

env:
  global:
    - secure: "pVcpV/al5Q607TbRzl/sbkdsx5hUjxehaJm6t5tgWrFn45icwdZrPw3JWcpt0R57NhPvXHxcJdm4WBtcGElWoDtR52QOW3yYh+gRw23y1MJg+5qHIbh5R1sOC/fLJ9TzQzvvRH5QQ5bKIe1hRQW9Cpqm7nX5Zhq6SqnAzcG1emE="
    - secure: "idzTTvCWmC0TYgYxQFOaZju86TUzKLaMKs2ZZsGloklf0mk0d3XH/CD5VYDPgP++/7Kmw9zC401EZyRC6anZYB0qCXwRulgux2Io5HCWChIrZTSx3DoSl+VRVi0cUkfMNomrwduJ0g1vVnDXp6xM8ITE574jwpasUJ2MOvVykdU="

addons:
  coverity_scan:
    project:
      name: "maxmind/MaxMind-DB-Reader-python"
      description: "Build submitted via Travis CI"
    notification_email: dev-ci@maxmind.com
    build_command_prepend: "python setup.py clean"
    build_command:   "python setup.py build"
    branch_pattern: .*coverity.*
