language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy

before_install:
  - git submodule update --init --recursive
  - git clone --recursive git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - pip install coverage coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install pylint yapf; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then export MM_FORCE_EXT_TESTS=1; fi
  - CFLAGS="-Werror -Wall -Wextra" coverage run --source maxminddb setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pylint --rcfile .pylintrc maxminddb/*.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then ./.travis-yapf.sh; fi

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dev-ci@maxmind.com
    on_success: change
    on_failure: always

env:
  global:
   - secure: "pVcpV/al5Q607TbRzl/sbkdsx5hUjxehaJm6t5tgWrFn45icwdZrPw3JWcpt0R57NhPvXHxcJdm4WBtcGElWoDtR52QOW3yYh+gRw23y1MJg+5qHIbh5R1sOC/fLJ9TzQzvvRH5QQ5bKIe1hRQW9Cpqm7nX5Zhq6SqnAzcG1emE="

addons:
  coverity_scan:
    project:
      name: "maxmind/MaxMind-DB-Reader-python"
      description: "Build submitted via Travis CI"
    notification_email: dev-ci@maxmind.com
    build_command_prepend: "python setup.py clean"
    build_command:   "python setup.py build"
    branch_pattern: .*coverity.*
