name: Create Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # The extension currently does not build on windows-latest.
        # We have a follow-up story for that.
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD_VERBOSITY: 1
          MAXMINDDB_REQUIRE_EXTENSION: 1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
